[general]
handlers = ["pushover", "smtp"]
refresh_interval = 900

[pushover]
app_token = ""
user_token = ""

[smtp]
server = ""
port = 587
security = ""  # STARTTLS or SSL
sender_email = ""
password = ""
receiver_emails = []