[project]
name = "usni-fleet-tracker-feed"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]
